os:
  - linux
sudo: required
language: cpp
dist: trusty
env:
  - TRAVIS_NODE_VERSION="12.3.1"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - valgrind
      - python-pip
before_install:
  - gcc -v
  - g++ -v
  - cmake --version
install:
  - >-
    rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm &&
    (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source
    ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - node --version
  - npm --version
  - npm i
  - sudo pip install --upgrade pip
  - sudo pip install gcovr
script:
  - npm run x64-build -- --type=Debug --folder=build-debug
  - cd build-debug
  - ctest -V -T memcheck && cat Testing/Temporary/MemoryChecker.*.log
  - make coverage
  - cd ..
  - npm run x64-build -- --type=Release --folder=build-release
  - npm run node-build
