os:
  - linux
sudo: required
language: cpp
dist: trusty

env:
- TRAVIS_NODE_VERSION="10.15.0"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - valgrind
      - python-pip

before_install:
  - gcc -v
  - g++ -v
  - cmake --version

install:
  # Clear out whatever version of NVM Travis has.
  # Grab NVM and checkout the latest stable tag.
  # Install the desired version of Node
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - node --version
  - npm --version
  - npm i
  - sudo pip install --upgrade pip
  - sudo pip install gcovr

script:
  # Debug build
  - sh ./runbuild.sh Debug build-debug
  - cd build-debug && ctest -T memcheck && cat Testing/Temporary/MemoryChecker.*.log"
  - cd build-debug && make coverage

  # Release build
  - sh ./runbuild.sh Release build-release

  # Node integration build
  - npm run build
