
name: CI Build

on: [push]

jobs:
  build:

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              name: "Ubuntu GCC-7",
              os: ubuntu-latest,
              gcc: 7
            }

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        env:
          CC: gcc-${{ matrix.config.gcc }}
          CXX: g++-${{ matrix.config.gcc }}
        run: npm install

      - name: Code styling
        run: npm run lint

      - name: Debug build + unit tests + code coverage
        run: |
          npm run x64-build -- --type=Debug --folder=build-debug
          npm run x64-tests -- --folder=build-debug --memcheck
          npm run x64-coverage -- --folder=build-debug

      - name: Release build
        run: npm run x64-build -- --type=Release --folder=build-release

      - name: Node N-API integration build
        run: npm run node-build
